version: "3"

services:
  wordpress:
    build: ./docker/wordpress_xdebug
    image: wordpress-xdebug
    container_name: woocommerce_stripe_wordpress
    restart: always
    depends_on:
      - db
    links:
      - db:mysql
    ports:
      - "8082:80"
    env_file:
      - default.env
    volumes:
      - ./docker/wordpress:/var/www/html/
      - ./docker/logs/apache2/:/var/log/apache2
      - .:/var/www/html/wp-content/plugins/woocommerce-gateway-stripe
      - ./tests/phpunit:/var/www/html/wp-content/plugins/woocommerce-gateway-stripe/tests/phpunit
      - ./docker/dev-php.ini:/usr/local/etc/php/conf.d/dev-php.ini
      - ./docker/bin:/var/scripts
  db:
    container_name: woocommerce_stripe_mysql
    image: mariadb:10.5.8
    ports:
      - "5678:3306"
    env_file:
      - default.env
    volumes:
      - ./docker/data:/var/lib/mysql
  phpMyAdmin:
    container_name: woocommerce_stripe_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8083:80"
    env_file:
      - default.env
