name: PHP tests

on:
  pull_request

jobs:
  beta-compatibility:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        woocommerce: [ 'beta' ]
        wordpress:   [ 'latest' ]
        php:         [ '7.0', '7.4', '8.0' ]
          
    
    name: Beta (PHP=${{ matrix.php }}, WP=${{ matrix.wordpress }}, WC=${{ matrix.woocommerce }})
    env:
      PHP_VERSION: ${{ matrix.php }}
      WP_VERSION:  ${{ matrix.wordpress }}
      WC_VERSION:  ${{ matrix.woocommerce }}
    steps:
      - name: Testing with PHP=${{ matrix.php }}, WP=${{ matrix.wordpress }}, WC=${{ matrix.woocommerce }}
        uses: actions/checkout@v2

      - name: Set up dependencies caching
        uses: actions/cache@v2
        with:
          path: ~/.cache/composer/
          key:  ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage:    none
          
      - name: If PHP 7.0, set up PHPUnit 6.5 for legacy compatibility
        if: ${{ matrix.php == '7.0' }}
        run: wget https://phar.phpunit.de/phpunit-6.5.14.phar && mv phpunit-6.5.14.phar phpunit.phar

      - name: If PHP 8.0 and WP 5.9, set up PHPUnit 9.5 for compatibility
        if: ${{ matrix.php == '8.0' && matrix.wordpress == '5.9' }}
        run: wget https://phar.phpunit.de/phpunit-9.5.13.phar && mv phpunit-9.5.13.phar phpunit.phar

      - name: Run CI checks
        run: bash bin/run-ci-tests.bash
