name: PHP tests

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast:    false
      max-parallel: 10
      matrix:
        woocommerce_support_policy: [ 'L', 'L-1', 'L-2' ]
        wordpress_support_policy:   [ 'L', 'L-1', 'L-2' ]
        php_support_policy:         [ 'L', 'L-1', 'L-2' ]
        include:
          # WooCommerce
          - woocommerce_support_policy: L
            woocommerce: '7.4.1'
          - woocommerce_support_policy: L-1
            woocommerce: '7.2.3'
          - woocommerce_support_policy: L-2
            woocommerce: '7.1.1'
          # WordPress
          - wordpress_support_policy: L
            wordpress: '6.1'
          - wordpress_support_policy: L-1
            wordpress: '6.0'
          - wordpress_support_policy: L-2
            wordpress: '5.9'
          # PHP
          - php_support_policy: L
            php: '8.0'
          - php_support_policy: L-1
            php: '7.4'
          - php_support_policy: L-2
            php: '7.3'

    name: Stable (PHP=${{ matrix.php_support_policy }}, WP=${{ matrix.wordpress_support_policy }}, WC=${{ matrix.woocommerce_support_policy }})
    env:
      PHP_VERSION: ${{ matrix.php }} 
      WP_VERSION:  ${{ matrix.wordpress }}
      WC_VERSION:  ${{ matrix.woocommerce }}
    steps:
      - name: Testing with PHP=${{ matrix.php }}, WP=${{ matrix.wordpress }}, WC=${{ matrix.woocommerce }}
        uses: actions/checkout@v2

      - name: Set up dependencies caching
        uses: actions/cache@v2
        with:
          path: ~/.cache/composer/
          key:  ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage:    none

      - name: If PHP >= 8.0 and >= WP 5.9, set up PHPUnit 9.5 for compatibility
        if: ${{ matrix.php >= '8.0' && matrix.wordpress >= '5.9' }}
        run: wget https://phar.phpunit.de/phpunit-9.5.13.phar && mv phpunit-9.5.13.phar phpunit.phar

      - name: Run CI checks
        run: bash bin/run-ci-tests.bash
